---
# Homepage Einstellungen
# Datei: ~/docker/homepage/config/settings.yaml

title: Pi Dashboard
favicon: https://pi-hole.net/img/favicon.png

theme: dark
color: slate

headerStyle: clean
layout:
  pi-dns:
    style: row
    columns: 2
  pi-home:
    style: row
    columns: 3